### ISSUE TITLE
Hi, How about the performance in different datasets?  this version can reach the the theano version? Look forward for your kind help!

### ISSUE THREAD

**Issue by wqz960** [justusschock/deep_alignment_network_pytorch#1]
Can you provide me the pretrained model?

**Comment by justusschock** [comment]
Unfortunately I cannot provide you a pretrained model, and I haven't even trained a model on a freely-available dataset (the HELEN notebook is just to show the use), so I can't confirm that either (sorry!).

What I can confirm is, that on an internal dataset it reaches comparable results to the theano version.

**Comment by wqz960** [comment]
@justusschock It seems you did not provide the dataset preprocess script, can you provide it?

**Comment by wqz960** [comment]
@justusschock use shapedata to make data argument?

**Comment by justusschock** [comment]
it's all done in the [example notebook](https://github.com/justusschock/deep_alignment_network_pytorch/blob/master/notebooks/helen_example.ipynb) via `shapedata`.

The data isn't preprocessed completely before training, but it is done OTF during data loading via `shapenet`
